Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o: \
 ../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Inc/stm32f4xx_hal_conf.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Inc/main.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_def.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f446xx.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/CMSIS/Include/core_cm4.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/CMSIS/Include/core_cmInstr.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/CMSIS/Include/cmsis_gcc.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/CMSIS/Include/core_cmFunc.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/CMSIS/Include/core_cmSimd.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/CMSIS/Device/ST/STM32F4xx/Include/system_stm32f4xx.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h \
 /media/filippo/DATA/Programmazione/Drone/Drone/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc_ex